#Verification of Central Limit Theorem
#One simple way to state it is as follows: 
#The Central Limit Theorem states that if there is a population with mean mu and standard deviation sigma and one draws 
#sufficiently large random samples from the population with replacement, then the distribution of the sample means 
#will be approximately normal.

#Create random population data of reasonable size; values are uniformly distributed between min and max
pop_size <-100000
min_value <- 0
max_value <-100
set.seed(123)
population <- runif(pop_size, min = min_value, max = max_value)

#Compute actual mean and standard deviation of the population
mu <- mean(population)
sig <- sd(population)

#Design sampling mechanism - no. of sampling trials and sample size for each trial
trials = 100
sample_size = 50

#Generate sample statistics - draw a random sample and compute its mean; repeat the procedure for the selected no. of trials
mySample <- numeric(trials)
for (i in c(1:trials)) {
  spl <- sample(population, size = sample_size, replace = TRUE)
  mySample[i] <- mean(spl)
}

#Compute estimates for mean and standard deviation from the data generated by the trials
mu_estimate <- mean(mySample) # mean of sample means is a good estimate for population mean
sig_spl <- sd(mySample)
sig_estimate <- sig_spl*sqrt(sample_size) # standard deviation of sample means is biased and needs to be corrected

#Compare the estimated parameters with the actual ones
result <- data.frame("Population_mean" = mu,
                     "Estimated_mean" = mu_estimate,
                     "Population_sd" = sig,
                     "Estimated_sd" = sig_estimate)

print(result)
plot(density(mySample)) #should look like a normal distribution irrespective of the original population